### ISSUE TITLE
error with editing ffnt.xml

### ISSUE THREAD

**Issue by abuali129** [Atvaark/FoxEngine.TranslationTool#2]
I'm still trying on getting arabic support on MGSV and I have another issue.
It is with FfntTool, 
I extracted arabia.ffnt then I had both arabia.xml and arabia_0.png
the .xml file had no issue, it contains the correct character set for both Eng and Ara languages  
but the .png is a mess it is corrupted, here is  a sample
http://i.imgur.com/L2vAtY1.png

I used BMfont to create a bitmap to replace the corrupted one
http://i.imgur.com/1lESfBu.png

after that I had to change to value of each character inside the .xml to match it with the new bitmap.

put when I try to repack the .ffnt using the new .xml I get this error

---

G:\MGSV\MGSV_FfntTool\bin\Debug>FfntTool "G:\MGSV\MGSV_FfntTool\bin\Debug\arabia\arabia.xml"

Unhandled Exception: System.InvalidOperationException: There is an error in XML document (6, 111). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFfntFile.Read3_Glyph(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFfntFile.Read4_GlyphMap(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFfntFile.Read2_FfntEntry(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFfntFile.Read6_FfntFile(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFfntFile.Read7_FfntFile()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at FfntTool.Program.PackFfnt(String path, String fileName, String outputPath) in c:\Users\abual\Desktop\FoxEngine.TranslationTool-master\FfntTool\Program.cs:line 56
   at FfntTool.Program.Main(String[] args) in c:\Users\abual\Desktop\FoxEngine.TranslationTool-master\FfntTool\Program.cs:line 41

---

**Comment by Atvaark** [comment]
That one of the ffnt files can't be unpacked with the default settings is a [known issue](https://github.com/Atvaark/FoxEngine.TranslationTool/blob/master/FfntTool/Program.cs#L162) which can only be fixed by adding width and height options. All but the arabic ffnt files are squares, so by simply hard coding 1024x512 you could extract it.
![arabia_0.png](http://i.imgur.com/cER6v0C.png)

I can't help you with that stacktrace. It clearly says that it fails to convert a string to a number which probably happens because you're using an incompatible xml schema.

**Comment by abuali129** [comment]
So could you just give me the command line for unpacking the file with the width and height to write on CMD? sorry i'm a beginner and don't know how hard coding is done.
and also suggest a way to edit the xml that's compatible with the unpacked one.

**Comment by abuali129** [comment]
well I found the problem of repacking the .ffnt 
It caused by a value of HorizontalShift that I adjusted comparing with BMfont , it shows below zero
some -1  -2 -3 values, that's what is not accepted by FfntTool to repack

**Comment by Atvaark** [comment]
You should just fork the repository and
- If you want to unpack the font then edit the line I linked previously and use the constant dimensions for the arabic font. Or just use the image I provided.
- If you want to use negative numbers then change the unsigned int properties to signed int properties. I can't guarantee that the game can read theae values.

**Comment by Atvaark** [comment]
Since I didn't hear anything from you in two weeks I'm going to close this issue for now.
